server:
  port: 8082

spring:
  application:
    name: product-service
  cloud:
    openfeign:
      micrometer:
        enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},trace=%X{traceId:-},span=%X{spanId:-}]"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/