server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  cloud:
    openfeign:
      micrometer:
        enabled: true
logging:
  level:
    org.springframework: INFO



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
