server:
  port: 8888

spring:
  profiles:
    active: native  # use local folder mode (not git)

  cloud:
    config:
      server:
        native:
          search-locations: file:///home/tariq/personal/java-learning/micro-service-architecture/config-repo

logging:
  level:
    org.springframework.cloud: INFO
