server:
  port: 8888

spring:
  profiles:
    active: native  # use local folder mode (not git)

  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/java-learning/microservices-demo/config-repo

logging:
  level:
    org.springframework.cloud: INFO
